import type { InventoryStock, ItemCatalog, Station } from '../types'
import { StatusPill } from '../components/common/StatusPill'
import { EmptyState } from '../components/common/EmptyState'
import { formatDateTime, recordLabel, stationLabelById } from '../utils/display'
type Props = { inventoryStocks: InventoryStock[]; dataError?: string; catalogError?: string; stations: Station[]; itemCatalog?: ItemCatalog[] }
export function InventoryPage({ inventoryStocks, dataError, catalogError, stations, itemCatalog = [] }: Props) {
  const catalogMap = new Map(itemCatalog.map((item) => [item.item_catalog_id || item.item_id, item]))
  return <div className="page-container"><section className="panel"><div className="panel-header"><div><p className="eyebrow">STATION SUPPLY STATUS</p><h2>Inventory records ({inventoryStocks.length})</h2></div><span className="data-note">Movement history is not supplied by the loaded inventory API.</span></div>
    {dataError ? <div className="unavailable-state" role="status">Inventory data unavailable. {dataError}</div> : !inventoryStocks.length ? <EmptyState message="No inventory records returned by the API." /> : <>{catalogError && <div className="unavailable-state" role="status">Item catalog unavailable. API-provided stock item names are shown where present; unresolved catalog references remain unavailable.</div>}<div className="table-scroll"><table><thead><tr><th>Station</th><th>Item</th><th>Quantity</th><th>Safety stock</th><th>Reorder threshold</th><th>Condition</th><th>Last updated</th></tr></thead><tbody>{inventoryStocks.map((stock) => { const qty = stock.quantity == null ? null : Number(stock.quantity); const safety = stock.safety_stock_minimum == null ? null : Number(stock.safety_stock_minimum); const threshold = stock.reorder_threshold == null ? null : Number(stock.reorder_threshold); const known = qty != null && Number.isFinite(qty); const safetyKnown = safety != null && Number.isFinite(safety); const thresholdKnown = threshold != null && Number.isFinite(threshold); const belowSafety = known && safetyKnown && qty < safety; const belowReorder = known && thresholdKnown && qty < threshold; const condition = !known ? 'Unknown' : qty === 0 ? 'Critical - quantity is zero' : belowSafety ? 'Critical - below safety stock' : belowReorder ? 'Low - below reorder threshold' : safetyKnown || thresholdKnown ? 'Normal' : 'Unknown'; const rawItem = stock.item_name || (stock.item_catalog_id ? catalogMap.get(stock.item_catalog_id)?.name : null); const item = recordLabel(rawItem, stock.item_catalog_id, 'Item name unavailable'); return <tr key={stock.stock_id}><td>{stationLabelById(stock.station_id, stations)}</td><td>{item}</td><td>{known ? qty : 'Not provided'}</td><td>{safety ?? 'Not provided'}</td><td>{threshold ?? 'Not provided'}</td><td><StatusPill status={condition} tone={condition.startsWith('Critical') ? 'danger' : condition.startsWith('Low') ? 'warning' : condition === 'Normal' ? 'success' : 'neutral'} /></td><td>{stock.last_updated && !Number.isNaN(Date.parse(stock.last_updated)) ? formatDateTime(stock.last_updated, true) : 'Not provided'}</td></tr>})}</tbody></table></div></>}
  </section></div>
}
