import type { Expedition, Personnel, PersonnelAssignment, Station, TransportLeg } from '../types'
import { StatusPill } from '../components/common/StatusPill'
import { EmptyState } from '../components/common/EmptyState'
import { recordLabel, stationLabelById, transportLabelById } from '../utils/display'
type Props = { personnel: Personnel[]; personnelError?: string; assignmentsError?: string; assignments: PersonnelAssignment[]; stations: Station[]; expeditions: Expedition[]; transportLegs: TransportLeg[] }
export function PersonnelPage({ personnel, personnelError, assignmentsError, assignments, stations, expeditions, transportLegs }: Props) {
  return <div className="page-container"><section className="panel"><div className="panel-header"><div><p className="eyebrow">FIELD ROSTER</p><h2>{personnelError ? 'Personnel data unavailable' : `Personnel (${personnel.length})`}</h2><p className="data-note">Current station reflects the personnel record; assignments may include historical records.</p></div></div>
    {personnelError ? <div className="unavailable-state operational-error" role="status"><strong>PERSONNEL DATA UNAVAILABLE</strong><p>Unable to retrieve personnel records.</p><button type="button" className="btn-secondary" onClick={() => window.dispatchEvent(new Event('polaris:refresh'))}>Retry</button><details><summary>Technical details</summary>{personnelError}</details></div> : !personnel.length ? <EmptyState message="No personnel records returned by the API." /> : <div className="table-scroll"><table><thead><tr><th>Personnel</th><th>Role</th><th>Current station</th><th>Fitness</th><th>Record status</th></tr></thead><tbody>{personnel.map((person) => { const id = person.person_id || person.personnel_id || 'unresolved'; const name = recordLabel(person.name || [person.first_name, person.last_name].filter(Boolean).join(' '), person.employee_code || id, 'Personnel identity unavailable'); const stationId = person.assigned_station_id || person.primary_station_id; return <tr key={id}><td>{name}{person.employee_code && <small className="table-subtext">{person.employee_code}</small>}</td><td>{person.role_on_expedition || person.role || 'Not provided'}</td><td>{stationLabelById(stationId, stations)}</td><td>{person.fitness_status || 'Not provided'}</td><td><StatusPill status={person.status} /></td></tr>})}</tbody></table></div>}
  </section><section className="panel"><div className="panel-header"><div><p className="eyebrow">ASSIGNMENT RECORDS</p><h2>Assignments ({assignments.length})</h2></div></div>
    {assignmentsError ? <div className="unavailable-state operational-error" role="status"><strong>ASSIGNMENT DATA UNAVAILABLE</strong><p>Unable to retrieve personnel assignments.</p><button type="button" className="btn-secondary" onClick={() => window.dispatchEvent(new Event('polaris:refresh'))}>Retry</button><details><summary>Technical details</summary>{assignmentsError}</details></div> : !assignments.length ? <EmptyState compact message="No assignment records returned by the API." /> : <div className="table-scroll"><table><thead><tr><th>Person</th><th>Expedition</th><th>Station</th><th>Transport leg</th><th>Status</th><th>Assignment period</th></tr></thead><tbody>{assignments.map((assignment) => { const person = personnel.find((entry) => entry.person_id === assignment.personnel_id || entry.personnel_id === assignment.personnel_id); const expedition = expeditions.find((entry) => entry.expedition_id === assignment.expedition_id); const personName = recordLabel(person?.name || [person?.first_name, person?.last_name].filter(Boolean).join(' '), person?.employee_code || person?.person_id || person?.personnel_id, 'Unresolved personnel reference'); return <tr key={assignment.assignment_id}><td>{personName}{!person && <small className="table-subtext">Assignment exists, but personnel details were not returned by the API.</small>}</td><td>{expedition ? recordLabel(expedition.code || expedition.name, expedition.expedition_id) : assignment.expedition_id ? recordLabel(null, assignment.expedition_id) : 'Not provided'}</td><td>{stationLabelById(assignment.station_id, stations)}</td><td>{transportLabelById(assignment.leg_id, transportLegs)}</td><td><StatusPill status={assignment.status} /></td><td>{assignment.start_date || 'Not provided'} – {assignment.end_date || 'Current/unknown'}</td></tr>})}</tbody></table></div>}
  </section></div>
}
