import { useMemo, useState } from 'react'
import type { CargoItem, Personnel, PersonnelAssignment, Station, TransportLeg } from '../types'
import { StatusPill } from '../components/common/StatusPill'
import { EmptyState } from '../components/common/EmptyState'
import { formatDateTime, recordLabel, stationLabelByReference } from '../utils/display'
type Props = { transportLegs: TransportLeg[]; dataError?: string; cargoItems: CargoItem[]; personnel: Personnel[]; assignments: PersonnelAssignment[]; stations: Station[]; onCancelLeg: (id: string) => Promise<void>; onViewImpact: (id: string) => Promise<void>; cancelingLegId: string | null; impactLoading: boolean }
export function TransportPage({ transportLegs, dataError, cargoItems, personnel, assignments, stations, onCancelLeg, onViewImpact, cancelingLegId, impactLoading }: Props) {
  const [status, setStatus] = useState('all'); const [query, setQuery] = useState('')
  const filtered = useMemo(() => transportLegs.filter((leg) => (status === 'all' || (leg.status || '').toLowerCase() === status) && `${leg.code || ''} ${leg.origin || ''} ${leg.destination || ''} ${leg.mode || ''}`.toLowerCase().includes(query.toLowerCase())), [transportLegs, status, query])
  return <div className="page-container"><section className="panel"><div className="panel-header"><div><p className="eyebrow">MOVEMENT OPERATIONS</p><h2>{dataError ? 'Transport data unavailable' : `Transport legs (${filtered.length})`}</h2></div><div className="toolbar-group"><label>Status <select className="select-input" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All</option><option value="planned">Planned</option><option value="in_transit">In transit</option><option value="delayed">Delayed</option><option value="cancelled">Cancelled</option><option value="completed">Completed</option></select></label><label>Search <input className="text-input" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Code, route, mode" /></label></div></div>
    {dataError ? <div className="unavailable-state" role="status">Transport data unavailable. {dataError}</div> : filtered.length === 0 ? <EmptyState message="No transport legs match the available data and filters." /> : <div className="table-scroll"><table><thead><tr><th>Leg</th><th>Route / mode</th><th>Planned departure</th><th>Planned arrival</th><th>Status / priority</th><th>Related cargo</th><th>Personnel</th><th>Actions</th></tr></thead><tbody>{filtered.map((leg) => { const cargo = cargoItems.filter((item) => item.leg_id === leg.leg_id); const assigned = assignments.filter((item) => item.leg_id === leg.leg_id); const names = assigned.map((assignment) => { const person = personnel.find((item) => item.person_id === assignment.personnel_id || item.personnel_id === assignment.personnel_id); return recordLabel(person?.name || [person?.first_name, person?.last_name].filter(Boolean).join(' '), person?.employee_code || (person?.person_id ?? person?.personnel_id), 'Unresolved personnel reference') }); return <tr key={leg.leg_id}><td>{recordLabel(leg.code, leg.leg_id)}</td><td>{stationLabelByReference(leg.origin, stations, 'origin')} → {stationLabelByReference(leg.destination, stations, 'destination')}<small className="table-subtext">{leg.mode || 'Mode not provided'}</small></td><td>{leg.planned_departure && !Number.isNaN(Date.parse(leg.planned_departure)) ? formatDateTime(leg.planned_departure, true) : 'Not provided'}</td><td>{leg.planned_arrival && !Number.isNaN(Date.parse(leg.planned_arrival)) ? formatDateTime(leg.planned_arrival, true) : 'Not provided'}</td><td><StatusPill status={leg.status} /><small className="table-subtext">Priority not provided by API</small></td><td>{cargo.length ? cargo.map((item) => recordLabel(item.tracking_code, item.cargo_id)).join(', ') : 'No linked cargo in loaded data'}</td><td>{names.length ? names.join(', ') : 'No linked assignment in loaded data'}</td><td><div className="btn-group"><button type="button" className="btn-secondary-sm" disabled={impactLoading} onClick={() => void onViewImpact(leg.leg_id)}>Impact</button>{(leg.status || '').toLowerCase() === 'planned' && <button type="button" className="btn-danger-sm" disabled={cancelingLegId === leg.leg_id} onClick={() => void onCancelLeg(leg.leg_id)}>{cancelingLegId === leg.leg_id ? 'Requesting...' : 'Cancel leg'}</button>}</div></td></tr> })}</tbody></table></div>}
  </section></div>
}
